version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: counter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - counter-network

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/counter_db
    depends_on:
      - db
    networks:
      - counter-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - counter-network

volumes:
  postgres_data:

networks:
  counter-network:
    driver: bridge 